name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
   unit:
    strategy:
      matrix:
        platform: [ubuntu-24.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        ROCKSDB_SHA=$(cd deps/rocksdb && git rev-parse HEAD)
        echo "ROCKSDB_SHA is $ROCKSDB_SHA"
        echo "ROCKSDB_SHA=$ROCKSDB_SHA" >> $GITHUB_ENV
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ env.ROCKSDB_SHA }}
    - name: unit-test
      run: |
          sudo apt-get update
          sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6 liburing-dev libevent-dev libgoogle-glog-dev
          LD_LIBRARY_PATH=/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/glog/lib:/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/libevent/lib make SWAP=1 unit-test -j8

   mem:
    strategy:
      matrix:
        platform: [ubuntu-24.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        ROCKSDB_SHA=$(cd deps/rocksdb && git rev-parse HEAD)
        echo "ROCKSDB_SHA is $ROCKSDB_SHA"
        echo "ROCKSDB_SHA=$ROCKSDB_SHA" >> $GITHUB_ENV
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ env.ROCKSDB_SHA }}
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6 liburing-dev libevent-dev libgoogle-glog-dev
          make -j8
    - name: make test
      run: LD_LIBRARY_PATH=/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/glog/lib:/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/libevent/lib  make test
   swap:
    strategy:
      matrix:
        platform: [ubuntu-24.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        ROCKSDB_SHA=$(cd deps/rocksdb && git rev-parse HEAD)
        echo "ROCKSDB_SHA is $ROCKSDB_SHA"
        echo "ROCKSDB_SHA=$ROCKSDB_SHA" >> $GITHUB_ENV
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ env.ROCKSDB_SHA }}
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6 liburing-dev libevent-dev libgoogle-glog-dev
          make SWAP=1 -j8
    - name: make test
      run: LD_LIBRARY_PATH=/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/glog/lib:/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/libevent/lib  make SWAP=1 test-disk
   swap-asan:
    strategy:
      matrix:
        platform: [ubuntu-24.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        ROCKSDB_SHA=$(cd deps/rocksdb && git rev-parse HEAD)
        echo "ROCKSDB_SHA is $ROCKSDB_SHA"
        echo "ROCKSDB_SHA=$ROCKSDB_SHA" >> $GITHUB_ENV
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ env.ROCKSDB_SHA }}
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6 liburing-dev libevent-dev libgoogle-glog-dev
          make SWAP=1 SANITIZER=address -j8
    - name: make test
      run: LD_LIBRARY_PATH=/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/glog/lib:/home/runner/work/Redis-On-Rocks/Redis-On-Rocks/deps/rocksdb/_build_folly/libs/libevent/lib  make SWAP=1 test-asan-disk



