name: CI

on: 
  push:
    branches: [ xredis_2_ror ]
  pull_request:
    branches: [ xredis_2_ror ]

jobs:
   mem:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: rocksdb
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
          make -j8
    - name: make test
      run: make test
   swap:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: rocksdb
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
          make -j8
    - name: make test
      run: make test-disk

