name: CI

on: 
  push:
    branches: [ xredis_2_ror ]
  pull_request:
    branches: [ xredis_2_ror ]

jobs:
   mem:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install librocksdb-dev libsnappy-dev zlib1g-dev libgflags-dev libstdc++6
          make
    - name: make test
      run: make test
   swap:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
          sudo apt-get update
          sudo apt-get -y install librocksdb-dev libsnappy-dev zlib1g-dev libgflags-dev libstdc++6
          make
    - name: make test
      run: make test-disk

