name: Daily

on:
  pull_request:
    branches:
      # any PR to a release branch.
      - '[0-9].[0-9]'
      - 'ror-[0-9].[0-9].[0-9]'
  schedule:
    - cron: '0 0 * * *'

jobs:

  build-cache-rocksdb:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    if: github.repository == 'ctripcorp/redis'
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: get rocksdb sha
      id: rocksdb-sha
      run: |
        echo "::set-output name=sha::$(cd deps/rocksdb && git rev-parse HEAD)"
      shell: bash
    - name: cache rocksdb
      id: cache-rocksdb
      uses: actions/cache@v3
      with:
        path: deps/rocksdb
        key: ${{ runner.os }}-rocksdb-${{ steps.rocksdb-sha.outputs.sha }}
    - name: make
      run: |
        sudo apt-get update
        sudo apt-get -y install libsnappy-dev zlib1g-dev libstdc++6
        make -j8

  test-ubuntu-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: test
      run: |
        sudo apt-get install tcl8.6
        ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster
    - name: unittest
      run: ./src/redis-server test all

  test-ubuntu-libc-malloc:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make MALLOC=libc
    - name: test
      run: |
        sudo apt-get install tcl8.6
        ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster

  test-ubuntu-io-threads:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make
    - name: test
      run: |
        sudo apt-get install tcl8.6 tcl-tls
        ./runtest --config io-threads 4 --config io-threads-do-reads yes --accurate --verbose --tags network --dump-logs
    - name: cluster tests
      run: |
        ./runtest-cluster --config io-threads 4 --config io-threads-do-reads yes

  test-valgrind:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make valgrind REDIS_CFLAGS='-Werror -DREDIS_TEST'
    - name: test
      run: |
        sudo apt-get update
        sudo apt-get install tcl8.6 valgrind -y
        ./runtest --valgrind --verbose --clients 1 --tags -large-memory --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --valgrind --no-latency --verbose --clients 1
    - name: unittest
      run: |
        valgrind --track-origins=yes --suppressions=./src/valgrind.sup --show-reachable=no --show-possibly-lost=no --leak-check=full --log-file=err.txt ./src/redis-server test all
        if grep -q 0x err.txt; then cat err.txt; exit 1; fi

  test-centos7-jemalloc:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    container: centos:7
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        yum -y install gcc make
        make
    - name: test
      run: |
        yum -y install which tcl
        ./runtest --accurate --verbose --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster

  test-macos-latest:
    runs-on: macos-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: test
      run: |
        ./runtest --accurate --verbose --no-latency --dump-logs
    - name: module api test
      run: ./runtest-moduleapi --verbose
    - name: sentinel tests
      run: ./runtest-sentinel
    - name: cluster tests
      run: ./runtest-cluster

  test-sanitizer-address:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make SANITIZER=address REDIS_CFLAGS='-DREDIS_TEST -Werror'
      - name: testprep
        run: |
          sudo apt-get update
          sudo apt-get install tcl8.6 tclx -y
      - name: test
        run: ./runtest --accurate --verbose --dump-logs
      - name: module api test
        run: ./runtest-moduleapi --verbose --dump-logs
      - name: sentinel tests
        run: ./runtest-sentinel
      - name: cluster tests
        run: ./runtest-cluster
      - name: unittest
        run: ./src/redis-server test all

  test-sanitizer-undefined:
    runs-on: ubuntu-latest
    if: github.repository == 'ctripcorp/redis'
    timeout-minutes: 14400
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make SANITIZER=undefined REDIS_CFLAGS='-DREDIS_TEST -Werror'
      - name: testprep
        run: |
          sudo apt-get update
          sudo apt-get install tcl8.6 tclx -y
      - name: test
        run: ./runtest --accurate --verbose --dump-logs
      - name: module api test
        run: ./runtest-moduleapi --verbose --dump-logs
      - name: sentinel tests
        run: ./runtest-sentinel
      - name: cluster tests
        run: ./runtest-cluster
      - name: unittest
        run: ./src/redis-server test all
